[tools]
#act = "0.2.87"
actionlint = "1.7.12"
#ant = "1.10.16"
"asdf:boris-ning-usds/asdf-azure-cli" = "2.84.0"
"asdf:fartbagxp/asdf-trippy" = "0.13.0"
#"asdf:fartbagxp/asdf-oauth2c" = "1.19.0"
#"asdf:log2/asdf-step" = "0.30.2"
awscli = "2.34.24"
black = "26.3.1"
#"cargo:lstr" = "0.2.1"
#"cargo:rkik" = "2.1.0"
"cargo:zizmor" = "1.23.1"
cf = "8.18.0"
cosign = "3.0.5"
deno = "2.7.11"
#dotnet = "10.0.201"
flyctl = "0.4.29"
gallery-dl = "1.31.10"
github-cli = "2.89.0"
"github:asciinema/asciinema" = "3.2.0"
"github:betterleaks/betterleaks" = "1.1.1"
"github:clever/csvlint" = "0.3.0"
#"github:dolthub/dolt" = "1.85.0"
#"github:duckdb/duckdb" = "1.5.1"
#"github:google/yamlfmt" = "0.21.0"
#"github:kbknapp/cargo-outdated" = "0.18.0"
#"github:maxmind/mmdbinspect" = "2.0.0"
"github:newren/git-filter-repo" = "2.47.0"
"github:qpdf/qpdf" = "12.3.2"
"github:praetorian-inc/titus" = "1.1.10"
"github:ramonvermeulen/whosthere" = "0.4.0"
#"github:runpod/runpodctl" = "2.1.9"
#"github:seeyebe/gmap" = "0.4.0"
#"github:square/certigo" = "1.17.1"
"github:trufflesecurity/trufflehog" = "3.94.1"
"github:unfrl/dug" = "0.0.94"
#"github:versent/saml2aws" = "2.36.19"
go = "1.26.1"
#"go:github.com/boostsecurityio/poutine" = "1.0.8"
#"go:github.com/github/git-sizer" = "1.5.0"
#"go:github.com/htmlparser/htmlparser" = "0.4.0"
#"go:github.com/plutov/oq" = "0.0.22"
#"go:github.com/projectdiscovery/dnsx/cmd/dnsx" = "1.2.3"
#"go:github.com/projectdiscovery/httpx/cmd/httpx" = "1.9.0"
#"go:github.com/projectdiscovery/subfinder/v2/cmd/subfinder" = "2.13.0"
#"go:github.com/reteps/dockerfmt" = "0.3.9"
#"go:github.com/six-ddc/plow" = "1.3.2"
"go:github.com/stacklok/frizbee" = "0.1.10"
#gradle = "8.9.0"
grype = "0.110.0"
helm = "4.1.3"
hugo = "0.160.0"
java = "openjdk-21.0.2"
#kind = "0.31.0"
kubectl = "1.35.3"
maven = "3.9.14"
mdbook = "0.5.2"
mitmproxy = "9.0.1"
"npm:actions-up" = "1.12.0"
"npm:@anthropic-ai/claude-code" = "2.1.92"
"npm:@googleworkspace/cli" = "0.22.5"
node = "24.14.1"
#oc = "1.12.0"
#packer = "1.15.1"
pipx = "1.11.1"
"pipx:asstosrt" = "0.1.6"
"pipx:agentseal" = "0.6.2"
"pipx:chardet" = "7.4.0.post2"
"pipx:checkov" = "3.2.513"
#"pipx:check-jsonschema" = "0.37.1"
"pipx:claude-code-transcripts" = "0.6"
"pipx:copyparty" = "1.20.13"
#"pipx:datasette" = "0.65.2"
#"pipx:llm" = "0.30"
"pipx:mkdocs" = "1.6.1"
"pipx:pre-commit" = "4.5.1"
#"pipx:pyasstosrt" = "1.5.0"
#"pipx:semgrep" = "1.157.0"
#"pipx:sslyze" = "6.3.1"
#"pipx:vastai" = "0.5.0"
"pipx:zensical" = "0.0.31"
pnpm = "10.3.0"
#poetry = "2.3.3"
python = "3.13.12"
ripgrep = "15.1.0"
ruby = "3.2.10"
ruff = "0.15.9"
rust = "1.94.1"
#sbt = "1.10.7"
#scala = "2.13.16"
#shellcheck = "0.11.0"
#shfmt = "3.12.0"
#sqlite = "3.52.0"
#steampipe = "2.4.0"
#syft = "1.42.3"
#terraform = "1.42.3"
#terraformer = "0.8.30"
#websocat = "1.14.1"
uv = "0.10.9"
#yarn = "4.9.4"
yq = "4.52.5"
yt-dlp = "2026.03.17"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "python"]
